{-# LANGUAGE OverloadedStrings #-}

module Views.Wedding where

import qualified Data.Map      as Map
import           Miso          (View)
import           Miso.Html
import qualified Miso.String   as Miso

import           Action
import           Model


weddingView :: Model -> View Action
weddingView _ =
          main_ [ id_ "content", class_ "white-background" ]
            [ div_ [ class_ "container single" ]
              [ div_ [ class_ "row" ]
                [ div_ [ class_ "col-12" ]
                  [ div_ [ class_ "post-featured-image" ]
                    [ img_ [ src_ "https://scontent-cph2-1.xx.fbcdn.net/v/t31.0-8/20449176_10155586457802888_7483912760165311604_o.jpg?_nc_cat=101&_nc_sid=8bfeb9&_nc_ohc=Cfbg4dtOboAAX_mGCZd&_nc_ht=scontent-cph2-1.xx&oh=d8ac90366bd51d5973d93e5da5c35562&oe=5FAC2350", width_ "1180", height_ "680", alt_ "" ]
                    ]
                  ]
                , div_ [ class_ "col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2" ]
                  [ article_ [ class_ "post has-thumbnail" ]
                    [ div_ [ class_ "post-header" ]
                      [ h2_ [] [ text "Jóhanna og Peter's Bryllup!" ]
                      , p_ [ class_ "meta-info" ]
                        [ span_ [ class_ "post-author" ] [ text "af ", a_ [ href_ "mailto:johannatummasardottir@gmail.com" ] [ text "Jóhanna og Peter" ] ]
                        , span_ [ class_ "post-date" ] [ text "14. August 2020" ]
                        ]
                      ]
                    , div_ [ class_ "post-content" ]
                      [ p_ [] [ text "This is a test to see if it actually works, and it seems it does! Let's see how it looks with more text" ]
                        , p_ [] [ text "Let's add another paragraph, and more text to see how it formats" ]
                      ]
                      , div_ [ class_ "grey-box", style_ $ Map.fromList [ (Miso.pack "background", Miso.pack "url(static/images/sample-square.png) center bottom no-repeat")
                                                                      , (Miso.pack "background-size", Miso.pack "cover")
                                                                      ] ]
                      [ div_ [  id_ "address-selector", class_ "overlay eq-height" ]
                        [ div_ [ id_ "address-NLD", class_ "address-container active" ]
                          [ div_ [ class_ "address-details" ]
                            [ h1_ [] [ text "We're here!" ]
                            , ul_ [ class_ "ul-custom-bullet" ]
                              [ li_ [] [ i_ [ class_ "saulticon-map" ] [], text "Test test", br_ [], text "test 1234", br_ [], text "Denmark" ]
                              , li_ [] [ i_ [ class_ "saulticon-call" ] [], text "1231241234123123" ]
                              , li_ [] [ i_ [ class_ "saulticon-mail" ] [], text "test@test.com" ]
                              ]
                            ]
                          , div_ [ class_ "map" ]
                              [ iframe_ [ width_ "600", height_ "450", style_ $ Map.singleton (Miso.pack "border") (Miso.pack "0"), src_ "https://www.google.com/maps/embed/v1/place?key=AIzaSyBgsIWBq3RlVwJ3msi0277fxh4gZgWLY8c&q=52.3746634,4.8592912&zoom=15&maptype=roadmap" ] []
                              ]
                          ]
                        , a_ [ href_ "#", class_ "bottom-button" ]
                            [ span_ [ class_ "show-layer" ] [ text "Locate on map", i_ [ class_ "saulticon-arrow-up" ] [] ]
                            , span_ [ class_ "hide-layer" ] [ text "Close map", i_ [ class_ "saulticon-arrow-down" ] [] ]
                            ]
                        ]
                      ]
                    ]
                  ]
                  , div_ [ class_ "col-md-6" ]
                      [ div_ [ class_ "grey-box", style_ $ Map.fromList [ (Miso.pack "background", Miso.pack "url(static/images/sample-square.png) center bottom no-repeat")
                                                                      , (Miso.pack "background-size", Miso.pack "cover")
                                                                      ] ]
                      [ div_ [  id_ "address-selector", class_ "overlay eq-height" ]
                        [ div_ [ id_ "address-NLD", class_ "address-container active" ]
                          [ div_ [ class_ "address-details" ]
                            [ h1_ [] [ text "We're here!" ]
                            , ul_ [ class_ "ul-custom-bullet" ]
                              [ li_ [] [ i_ [ class_ "saulticon-map" ] [], text "Test test", br_ [], text "test 1234", br_ [], text "Denmark" ]
                              , li_ [] [ i_ [ class_ "saulticon-call" ] [], text "1231241234123123" ]
                              , li_ [] [ i_ [ class_ "saulticon-mail" ] [], text "test@test.com" ]
                              ]
                            ]
                          , div_ [ class_ "map" ]
                              [ iframe_ [ width_ "600", height_ "450", style_ $ Map.singleton (Miso.pack "border") (Miso.pack "0"), src_ "https://www.google.com/maps/embed/v1/place?key=AIzaSyBgsIWBq3RlVwJ3msi0277fxh4gZgWLY8c&q=52.3746634,4.8592912&zoom=15&maptype=roadmap" ] []
                              ]
                          ]
                        , a_ [ href_ "#", class_ "bottom-button" ]
                            [ span_ [ class_ "show-layer" ] [ text "Locate on map", i_ [ class_ "saulticon-arrow-up" ] [] ]
                            , span_ [ class_ "hide-layer" ] [ text "Close map", i_ [ class_ "saulticon-arrow-down" ] [] ]
                            ]
                        ]
                      ]
                  ]
                  , div_ [ class_ "col-md-6" ]
                      [ div_ [ class_ "grey-box", style_ $ Map.fromList [ (Miso.pack "background", Miso.pack "url(static/images/sample-square.png) center bottom no-repeat")
                                                                      , (Miso.pack "background-size", Miso.pack "cover")
                                                                      ] ]
                      [ div_ [  id_ "address-selector1", class_ "overlay eq-height" ]
                        [ div_ [ id_ "address-NLDTEST", class_ "address-container active" ]
                          [ div_ [ class_ "address-details" ]
                            [ h1_ [] [ text "We're here!" ]
                            , ul_ [ class_ "ul-custom-bullet" ]
                              [ li_ [] [ i_ [ class_ "saulticon-map" ] [], text "Test test", br_ [], text "test 1234", br_ [], text "Denmark" ]
                              , li_ [] [ i_ [ class_ "saulticon-call" ] [], text "1231241234123123" ]
                              , li_ [] [ i_ [ class_ "saulticon-mail" ] [], text "test@test.com" ]
                              ]
                            ]
                          , div_ [ class_ "map" ]
                              [ iframe_ [ width_ "600", height_ "450", style_ $ Map.singleton (Miso.pack "border") (Miso.pack "0"), src_ "https://www.google.com/maps/embed/v1/place?key=AIzaSyBgsIWBq3RlVwJ3msi0277fxh4gZgWLY8c&q=52.3746634,4.8592912&zoom=15&maptype=roadmap" ] []
                              ]
                          ]
                        , a_ [ href_ "#", class_ "bottom-button" ]
                            [ span_ [ class_ "show-layer" ] [ text "Locate on map", i_ [ class_ "saulticon-arrow-up" ] [] ]
                            , span_ [ class_ "hide-layer" ] [ text "Close map", i_ [ class_ "saulticon-arrow-down" ] [] ]
                            ]
                        ]
                      ]
                  ]
                ]
              ]
            ]
