BEGIN;

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

COMMIT;
